env:
  jest: true
  node: true
plugins:
  - jest
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 2020
  sourceType: module
ignorePatterns: [/dist]
rules:
  no-console: 0
  import/extensions: 0
  arrow-parens: 0
  no-param-reassign: 0
  no-undef: 0

